name: build
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-20.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/

  deploy:
    if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
      - name: Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitMode: true
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          files-primary: "Artifacts/temmies_origins-*.jar"
          game-versions: "1.19.2"
          loaders: fabric

          changelog: ${{ steps.changelog.outputs.changelog }}